apiVersion: v1
kind: Service
metadata:
  name: jb-fe
  labels:
    name: jb-fe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: jb-fe
