# Use Dockerized infrastructure
sudo: false

# Use node_js environnement
language: node_js
node_js:
  - "6"

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

# Set envrionment variables
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - AUTHOR=pedrampejman
    - NODE_ENV=CI
      # Service directories
    - APP_DIR=app
    - FE_DIR=fe
    - GEN_DIR=gen
      # Kubernetes configuration
    - CLOUDSDK_COMPUTE_ZONE=us-east1-d
    - PROJECT_NAME=jukebox-161404
    - CLUSTER_NAME_PRD=jukebox-alpha
      # Image names
    - APP_IMAGE_NAME=jb-app
    - FE_IMAGE_NAME=jb-app
    - GEN_IMAGE_NAME=jb-gen
      # Container names
    - APP_CONTAINER_NAME=jb-app
    - FE_CONTAINER_NAME=jb-fe
    - GEN_CONTAINER_NAME=jb-gen
      # Deployment names
    - APP_DEPLOYMENT_NAME=jb-app
    - FE_DEPLOYMENT_NAME=jb-fe
    - GEN_DEPLOYMENT_NAME=jb-gen

# Build each service individually
install:
  - npm --silent --prefix ./$APP_DIR install ./$APP_DIR
  - npm --silent --prefix ./$FE_DIR install ./$FE_DIR

# Run unit tests
# TODO: Run integration tests
script:
  - npm --silent --prefix ./$APP_DIR test ./$APP_DIR

# Set up for deployment
before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

# Deploy to production 
deploy:
  - provider: script
    script: etc/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
