apiVersion: v1
kind: Service
metadata:
  name: jb-app
  labels:
    name: jb-app
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    name: jb-app
