apiVersion: v1
kind: Service
metadata:
  name: jb-app
  labels:
    name: jb-app
spec:
  type: LoadBalancer
  ports:
    - port: 34000
      targetPort: 34000
      protocol: TCP
  selector:
    name: jb-app
