apiVersion: v1
kind: Service
metadata:
  name: jb-gen
  labels:
    name: jb-gen
spec:
  type: LoadBalancer
  ports:
    - port: 35000
      targetPort: 35000
      protocol: TCP
  selector:
    name: jb-gen
